/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apiaries;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author boukbab
 */
public class Addapiary extends javax.swing.JFrame {
    Apiaries apia = new Apiaries();
    /**
     * Creates new form Add apiary
     * @throws java.text.ParseException
     */
    public Addapiary() throws ParseException {
        initComponents();
        Combofill(apia.dir(Constants.ABSULUTE_PATH));
        notif.setVisible(true);
        loc_txt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ref_txt = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        Add_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nb_frames = new javax.swing.JSpinner();
        time_txt = new javax.swing.JFormattedTextField();
        combo_loc = new javax.swing.JComboBox<>();
        loc_txt = new javax.swing.JFormattedTextField();
        date_txt = new com.toedter.calendar.JDateChooser();
        notif = new javax.swing.JLabel();
        new_loc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add appiary");
        setLocation(new java.awt.Point(550, 450));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Location:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 120, 90, 24);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel2.setText("Number of  frames in apiary :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 220, 290, 24);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 70, 70, 24);

        ref_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 172, 172), 1, true));
        ref_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(ref_txt);
        ref_txt.setBounds(170, 160, 300, 40);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel4.setText("Time:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 70, 60, 24);

        Add_btn.setBackground(new java.awt.Color(248, 196, 18));
        Add_btn.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        Add_btn.setText("Add");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Add_btn);
        Add_btn.setBounds(390, 280, 100, 40);

        cancel_btn.setBackground(new java.awt.Color(248, 196, 18));
        cancel_btn.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn);
        cancel_btn.setBounds(500, 280, 100, 40);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel5.setText("Reference:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 170, 120, 24);

        nb_frames.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(nb_frames);
        nb_frames.setBounds(350, 220, 60, 34);

        time_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 172, 172), 1, true));
        try {
            time_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        time_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(time_txt);
        time_txt.setBounds(360, 60, 110, 40);

        combo_loc.setBackground(new java.awt.Color(254, 254, 254));
        combo_loc.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        combo_loc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_locItemStateChanged(evt);
            }
        });
        combo_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_locActionPerformed(evt);
            }
        });
        jPanel1.add(combo_loc);
        combo_loc.setBounds(170, 110, 300, 39);

        loc_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 172, 172), 1, true));
        loc_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(loc_txt);
        loc_txt.setBounds(170, 110, 300, 40);

        date_txt.setDateFormatString("dd/M/ yyyy");
        date_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(date_txt);
        date_txt.setBounds(90, 60, 200, 40);

        notif.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        notif.setForeground(new java.awt.Color(154, 90, 24));
        notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/infounh.png"))); // NOI18N
        notif.setText("Fill in all informations about the apiary..");
        jPanel1.add(notif);
        notif.setBounds(40, 20, 420, 21);

        new_loc.setBackground(new java.awt.Color(254, 254, 254));
        new_loc.setText("new location");
        new_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_locActionPerformed(evt);
            }
        });
        jPanel1.add(new_loc);
        new_loc.setBounds(480, 120, 141, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        String date ="";
        if(date_txt.getDate()!=null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.format(date_txt.getDate()); 
        }
        String time =time_txt.getText();
        String loc  =loc_txt.getText();
        String ref  =ref_txt.getText();
        String frames= nb_frames.getValue().toString();
        String aloc =combo_loc.getSelectedItem().toString();
        if(!new_loc.isSelected()){
            if(date.equals("")||time.hashCode()<3||aloc.hashCode()==0
            ||ref.hashCode()==0){
                notif.setVisible(true);
                notif.setText("Inf: One of fields is empty!");
            }else{
                notif.setVisible(true);
                try {
                    notif.setText(apia.Add_apiary(date,time,aloc,
                            ref,frames));
                } catch (IOException ex) {
                    Logger.getLogger(Addapiary.class.getName()).log(Level.SEVERE, null, ex);
                }
                } 
            }else{
             if(date.equals("")||time.hashCode()<3||loc.hashCode()==0
                ||ref.hashCode()==0){
                    notif.setVisible(true);
                    notif.setText("Inf: One of fields is empty!");
                }else{
                    notif.setVisible(true);
                    try {
                        notif.setText(apia.Add_apiary(date,time,loc,
                                ref,frames));
                    } catch (IOException ex) {
                        Logger.getLogger(Addapiary.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    } 
        
        }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
         dispose();      
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void combo_locItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_locItemStateChanged
       
    }//GEN-LAST:event_combo_locItemStateChanged

    private void combo_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_locActionPerformed
        
    }//GEN-LAST:event_combo_locActionPerformed

    private void new_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_locActionPerformed

        if(new_loc.isSelected()){
        combo_loc.setVisible(false);
        loc_txt.setVisible(true);}else{
        combo_loc.setVisible(true);
        loc_txt.setVisible(false);
        }
    }//GEN-LAST:event_new_locActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Addapiary().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Addapiary.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
     private void Combofill(String [] curDir){      
        for(String d:curDir){
          combo_loc.addItem(d);}
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JComboBox<String> combo_loc;
    private com.toedter.calendar.JDateChooser date_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField loc_txt;
    private javax.swing.JSpinner nb_frames;
    private javax.swing.JRadioButton new_loc;
    private javax.swing.JLabel notif;
    private javax.swing.JFormattedTextField ref_txt;
    private javax.swing.JFormattedTextField time_txt;
    // End of variables declaration//GEN-END:variables
}
