/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apiaries;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author boukbab
 */
public class Editapiary extends javax.swing.JFrame {
    Apiaries apia = new Apiaries();
    public String oldloc;
    public String oldname;
    /**
     * Creates new form Add apiary
     * @throws java.text.ParseException
     */
    public Editapiary() throws ParseException {
        initComponents();
        notif.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ref_txt = new javax.swing.JFormattedTextField();
        save_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nb_frames = new javax.swing.JSpinner();
        loc_txt = new javax.swing.JFormattedTextField();
        notif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add appiary");
        setLocation(new java.awt.Point(550, 450));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Location:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 80, 90, 24);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel2.setText("Number of  frames in apiary :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 200, 290, 24);

        ref_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 172, 172), 1, true));
        ref_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(ref_txt);
        ref_txt.setBounds(160, 140, 300, 40);

        save_btn.setBackground(new java.awt.Color(248, 196, 18));
        save_btn.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn);
        save_btn.setBounds(360, 250, 100, 40);

        cancel_btn.setBackground(new java.awt.Color(248, 196, 18));
        cancel_btn.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn);
        cancel_btn.setBounds(470, 250, 100, 40);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel5.setText("Apiary:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 150, 120, 24);

        nb_frames.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(nb_frames);
        nb_frames.setBounds(340, 200, 60, 34);

        loc_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 172, 172), 1, true));
        loc_txt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jPanel1.add(loc_txt);
        loc_txt.setBounds(160, 80, 300, 40);

        notif.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        notif.setForeground(new java.awt.Color(154, 90, 24));
        notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/infounh.png"))); // NOI18N
        notif.setText("Edit informations about selected apiary");
        jPanel1.add(notif);
        notif.setBounds(40, 20, 420, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        String msg = "please modify some fields";
        if(!oldloc.equals(loc_txt.getText())||!oldname.equals(ref_txt.getText()))  { 
        msg= apia.Edit_apiary(oldloc,loc_txt.getText(),oldname,ref_txt.getText(),nb_frames.getValue().toString());}
        
        notif.setText(msg);
    }//GEN-LAST:event_save_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
         dispose();      
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editapiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Editapiary().setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(Editapiary.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JFormattedTextField loc_txt;
    public javax.swing.JSpinner nb_frames;
    private javax.swing.JLabel notif;
    public javax.swing.JFormattedTextField ref_txt;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables
}
