// -*- mode:java; encoding:utf-8 -*-
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apiaries;

import java.awt.Color;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author boukbab
 */
public class Login_window extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Login_window() {
        initComponents();
        txt_usr.setCaretColor(Color.WHITE);
        Pass_log.setCaretColor(Color.WHITE);
        notif_txt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_usr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Pass_log = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        notif_txt = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        access = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setLocation(new java.awt.Point(400, 200));
        setName("main_window"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(993, 700));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(105, 48, 44));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.window);
        jLabel3.setText("Sign in");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        txt_usr.setBackground(new java.awt.Color(105, 48, 44));
        txt_usr.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_usr.setForeground(new java.awt.Color(255, 245, 245));
        txt_usr.setBorder(null);
        txt_usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usrActionPerformed(evt);
            }
        });
        jPanel2.add(txt_usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 340, 48));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 390, 17));

        Pass_log.setBackground(new java.awt.Color(105, 48, 44));
        Pass_log.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pass_log.setForeground(new java.awt.Color(230, 230, 230));
        Pass_log.setBorder(null);
        Pass_log.setEchoChar('\u25cf');
        Pass_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_logActionPerformed(evt);
            }
        });
        jPanel2.add(Pass_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 340, 48));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 227, 227));
        jLabel4.setText(" Password :");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 390, 10));

        notif_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        notif_txt.setForeground(new java.awt.Color(105, 48, 44));
        notif_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/info32.png"))); // NOI18N
        notif_txt.setText("msg");
        notif_txt.setToolTipText("");
        jPanel2.add(notif_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, -1));

        cancel.setBackground(new java.awt.Color(248, 248, 248));
        cancel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cancel.setForeground(new java.awt.Color(142, 23, 23));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 390, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(177, 177, 177));
        jLabel1.setText("Forgot password ? click here");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/lock.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/gly32.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 50));

        access.setBackground(new java.awt.Color(248, 248, 248));
        access.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        access.setForeground(new java.awt.Color(142, 23, 23));
        access.setText("Login ");
        access.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                accessMouseMoved(evt);
            }
        });
        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });
        jPanel2.add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 390, 50));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 227, 227));
        jLabel8.setText("Username / Email adress:");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(220, 200, 470, 470);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/banner.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pass_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_logActionPerformed
       accessActionPerformed(evt);  // TODO add your handling code here:
      
        
    }//GEN-LAST:event_Pass_logActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed
        // TODO add your handling code here:
        String txt= txt_usr.getText();
        String pss= Pass_log.getText();
        if (txt.trim().equals("ensias") && pss.trim().equals("miola")){
             Main frame = new Main();
             frame.setVisible(true);
              win_exit();
        }
        else{
             notif_txt.setVisible(true);
           notif_txt.setForeground(new Color(218,123,8));
           notif_txt.setText("Username or Password invalid !");
        }
    }//GEN-LAST:event_accessActionPerformed

    private void txt_usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usrActionPerformed

    private void accessMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessMouseMoved
      // access.setBackground(Color.yellow);
    }//GEN-LAST:event_accessMouseMoved

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
      // access.setBackground(new Color(218,123,8));
    }//GEN-LAST:event_jPanel2MouseMoved
    private void win_exit(){
        this.setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
         javax.swing.UIManager.getLookAndFeelDefaults().put("Table:\"Table.cellRenderer\".background", Color.WHITE);
        javax.swing.UIManager.getLookAndFeelDefaults().put("Table.background",new ColorUIResource(Color.WHITE));
        javax.swing.UIManager.getLookAndFeelDefaults().put("TableHeader.background",new ColorUIResource(new Color(105,48,44)));
        javax.swing.UIManager.getLookAndFeelDefaults().put("TableHeader.foreground",new ColorUIResource(Color.WHITE));
        javax.swing.UIManager.getLookAndFeelDefaults().put("Table.alternateRowColor",Color.white.brighter());
        javax.swing.UIManager.put("ProgressBar.setBackground", Color.WHITE);
        javax.swing.UIManager.put("ProgressBar.setForeground", new Color(0,128,0));
        javax.swing.UIManager.put("ProgressBar.selectionForeground", Color.WHITE);
        javax.swing.UIManager.put("ProgressBar.selectionBackground", Color.black);
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_window().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass_log;
    private javax.swing.JButton access;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel notif_txt;
    private javax.swing.JTextField txt_usr;
    // End of variables declaration//GEN-END:variables
}
