/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apiaries;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author boukbab
 */
public class Main extends javax.swing.JFrame {
    
    boolean editState=false;
    public Main() {
        
        initComponents();
        Pane_home.setVisible(true);
        viz_panel.setVisible(false);
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4}, new JPanel[]{ind_2,ind_3, ind_4});
        Apiaries apia = new Apiaries();
        if(!editState){
        Combofill(apia.dir(Constants.ABSULUTE_PATH));
        ListFill();}
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        side_pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        traffic_max = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        temp_max = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Pane_home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        apia_List = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        W_table = new javax.swing.JTable();
        combo_loc = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TT_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add_apia = new javax.swing.JButton();
        edit_apia = new javax.swing.JButton();
        delete_apia = new javax.swing.JButton();
        synchro_apia = new javax.swing.JButton();
        viz_panel = new javax.swing.JPanel();
        update_data = new javax.swing.JButton();
        combo_location = new javax.swing.JComboBox<>();
        combo_apia = new javax.swing.JComboBox<>();
        viz_data = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        name_dash = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 160));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(105, 48, 44));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_1.setBackground(new java.awt.Color(105, 48, 44));
        btn_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_1MouseMoved(evt);
            }
        });
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/apia.png"))); // NOI18N
        jLabel8.setText("Dashboard");

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, -1));

        btn_2.setBackground(new java.awt.Color(105, 48, 44));
        btn_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_2MouseMoved(evt);
            }
        });
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_2MouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/settings.png"))); // NOI18N
        jLabel9.setText("Settings");

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 113, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, -1));

        btn_3.setBackground(new java.awt.Color(105, 48, 44));
        btn_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_3MouseMoved(evt);
            }
        });
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/dataviz.png"))); // NOI18N
        jLabel10.setText("Data viz");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, -1));

        btn_4.setBackground(new java.awt.Color(105, 48, 44));
        btn_4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_4MouseMoved(evt);
            }
        });
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/users.png"))); // NOI18N
        jLabel11.setText("Users");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 138, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/galypmenu.png"))); // NOI18N
        jLabel12.setText("     Menu");
        side_pane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        side_pane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 240, 0));
        side_pane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 20));

        jPanel1.setBackground(new java.awt.Color(105, 48, 44));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("LM Roman Caps 10", 1, 75)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 231, 231));
        jLabel2.setText("G");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 67, 105);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(80, 70, 130, 10);

        jLabel7.setFont(new java.awt.Font("LM Roman Caps 10", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 231, 231));
        jLabel7.setText("  e s t i o n");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 70, 130, 26);

        jLabel13.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 231, 231));
        jLabel13.setText("ruchers");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(80, 30, 132, 54);

        side_pane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 140));

        jLabel3.setFont(new java.awt.Font("LM Roman Caps 10", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 231, 231));
        jLabel3.setText("rabat, morocco");
        side_pane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 740, 150, 20));

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 231, 231));
        jLabel1.setText("MIOLA");
        side_pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, 60));

        jLabel14.setFont(new java.awt.Font("LM Roman Caps 10", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 231, 231));
        jLabel14.setText("  e n s i a s");
        side_pane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 150, -1));

        jLabel15.setFont(new java.awt.Font("LM Roman Caps 10", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 231, 231));
        jLabel15.setText("2020");
        side_pane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, 60, 20));

        jLabel16.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/notfic.png"))); // NOI18N
        jLabel16.setText(" Notification");
        side_pane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        side_pane.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 20));

        jLabel17.setForeground(new java.awt.Color(255, 245, 245));
        jLabel17.setText("max traffic :");
        side_pane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 245, 245));
        jLabel18.setText("°C");
        side_pane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        traffic_max.setFont(new java.awt.Font("Ubuntu Light", 0, 50)); // NOI18N
        traffic_max.setForeground(new java.awt.Color(252, 252, 252));
        traffic_max.setText("----");
        side_pane.add(traffic_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 110, 80));

        jLabel20.setForeground(new java.awt.Color(255, 245, 245));
        jLabel20.setText("Current apiary");
        side_pane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        temp_max.setFont(new java.awt.Font("Ubuntu Light", 0, 50)); // NOI18N
        temp_max.setForeground(new java.awt.Color(252, 252, 252));
        temp_max.setText("----");
        side_pane.add(temp_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 110, 80));

        jLabel22.setForeground(new java.awt.Color(255, 245, 245));
        jLabel22.setText("max temp :");
        side_pane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 800));

        jPanel2.setBackground(new java.awt.Color(248, 196, 18));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1250, 10));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        Pane_home.setBackground(new java.awt.Color(255, 250, 246));
        Pane_home.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/ruchers.jpg"))); // NOI18N
        Pane_home.add(jLabel4);
        jLabel4.setBounds(0, 0, 638, 270);

        apia_List.setBorder(javax.swing.BorderFactory.createTitledBorder("Apiaries list"));
        apia_List.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        apia_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "R01     |01/05/2020_15:40  ", "R02     |01/05/2020_15:42  ", "R01     |01/05/2020_15:40 ", "R02     |01/05/2020_15:42 " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        apia_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        apia_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apia_ListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(apia_List);

        Pane_home.add(jScrollPane2);
        jScrollPane2.setBounds(20, 410, 600, 280);

        W_table.setAutoCreateRowSorter(true);
        W_table.setBackground(new java.awt.Color(254, 254, 254));
        W_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        W_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        W_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        W_table.setGridColor(new java.awt.Color(223, 189, 13));
        W_table.setRowHeight(25);
        W_table.setRowMargin(2);
        jScrollPane3.setViewportView(W_table);

        Pane_home.add(jScrollPane3);
        jScrollPane3.setBounds(640, 390, 610, 300);

        combo_loc.setBackground(new java.awt.Color(254, 254, 254));
        combo_loc.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        combo_loc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_locItemStateChanged(evt);
            }
        });
        combo_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_locActionPerformed(evt);
            }
        });
        Pane_home.add(combo_loc);
        combo_loc.setBounds(20, 350, 600, 50);

        TT_table.setAutoCreateRowSorter(true);
        TT_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TT_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TT_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TT_table.setCellSelectionEnabled(true);
        TT_table.setGridColor(new java.awt.Color(241, 196, 28));
        TT_table.setOpaque(false);
        TT_table.setRowHeight(25);
        TT_table.setRowMargin(2);
        TT_table.setShowVerticalLines(false);
        jScrollPane4.setViewportView(TT_table);

        Pane_home.add(jScrollPane4);
        jScrollPane4.setBounds(640, 40, 610, 310);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Traffic and Temperature [°C] in the apiaries");
        Pane_home.add(jLabel5);
        jLabel5.setBounds(650, 0, 510, 40);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Weight [g]");
        Pane_home.add(jLabel6);
        jLabel6.setBounds(870, 350, 170, 40);

        add_apia.setBackground(new java.awt.Color(254, 254, 254));
        add_apia.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        add_apia.setForeground(new java.awt.Color(5, 5, 5));
        add_apia.setText("Add apiary");
        add_apia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                add_apiaMouseMoved(evt);
            }
        });
        add_apia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_apiaActionPerformed(evt);
            }
        });
        Pane_home.add(add_apia);
        add_apia.setBounds(20, 290, 130, 40);

        edit_apia.setBackground(new java.awt.Color(254, 254, 254));
        edit_apia.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        edit_apia.setForeground(new java.awt.Color(5, 5, 5));
        edit_apia.setText("Edit");
        edit_apia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_apiaMouseMoved(evt);
            }
        });
        edit_apia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_apiaActionPerformed(evt);
            }
        });
        Pane_home.add(edit_apia);
        edit_apia.setBounds(180, 290, 130, 40);

        delete_apia.setBackground(new java.awt.Color(254, 254, 254));
        delete_apia.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        delete_apia.setForeground(new java.awt.Color(5, 5, 5));
        delete_apia.setText("Delete");
        delete_apia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                delete_apiaMouseMoved(evt);
            }
        });
        delete_apia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_apiaActionPerformed(evt);
            }
        });
        Pane_home.add(delete_apia);
        delete_apia.setBounds(330, 290, 130, 40);

        synchro_apia.setBackground(new java.awt.Color(254, 254, 254));
        synchro_apia.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        synchro_apia.setForeground(new java.awt.Color(5, 5, 5));
        synchro_apia.setText("Synchronize");
        synchro_apia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                synchro_apiaMouseMoved(evt);
            }
        });
        synchro_apia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synchro_apiaActionPerformed(evt);
            }
        });
        Pane_home.add(synchro_apia);
        synchro_apia.setBounds(480, 290, 140, 40);

        jPanel6.add(Pane_home);
        Pane_home.setBounds(0, 0, 1250, 740);

        viz_panel.setBackground(new java.awt.Color(254, 254, 254));

        update_data.setBackground(new java.awt.Color(254, 254, 254));
        update_data.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        update_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/synch.png"))); // NOI18N
        update_data.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        update_data.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                update_dataMouseMoved(evt);
            }
        });
        update_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_dataActionPerformed(evt);
            }
        });

        combo_location.setBackground(new java.awt.Color(254, 254, 254));
        combo_location.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        combo_location.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_locationItemStateChanged(evt);
            }
        });
        combo_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_locationActionPerformed(evt);
            }
        });

        combo_apia.setBackground(new java.awt.Color(254, 254, 254));
        combo_apia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        combo_apia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_apiaItemStateChanged(evt);
            }
        });
        combo_apia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_apiaActionPerformed(evt);
            }
        });

        viz_data.setPreferredSize(new java.awt.Dimension(1167, 560));

        javax.swing.GroupLayout viz_dataLayout = new javax.swing.GroupLayout(viz_data);
        viz_data.setLayout(viz_dataLayout);
        viz_dataLayout.setHorizontalGroup(
            viz_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1167, Short.MAX_VALUE)
        );
        viz_dataLayout.setVerticalGroup(
            viz_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viz_panelLayout = new javax.swing.GroupLayout(viz_panel);
        viz_panel.setLayout(viz_panelLayout);
        viz_panelLayout.setHorizontalGroup(
            viz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viz_panelLayout.createSequentialGroup()
                .addGroup(viz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viz_panelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(update_data, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_location, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(combo_apia, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viz_panelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(viz_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        viz_panelLayout.setVerticalGroup(
            viz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viz_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(viz_data, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(viz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_data, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_apia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );

        jPanel6.add(viz_panel);
        viz_panel.setBounds(0, 0, 1250, 743);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1250, 740));

        jPanel5.setBackground(new java.awt.Color(255, 254, 254));

        name_dash.setFont(new java.awt.Font("Liberation Mono", 1, 28)); // NOI18N
        name_dash.setText("Manage your Apiaries ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(name_dash)
                .addContainerGap(789, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_dash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 1250, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        Pane_home.setVisible(true);
        viz_panel.setVisible(false);
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4}, new JPanel[]{ind_2,ind_3, ind_4});
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
           Pane_home.setVisible(false);
        viz_panel.setVisible(true);
        
        
        
         setColor(btn_3); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_1,btn_4}, new JPanel[]{ind_2,ind_1, ind_4});
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
          setColor(btn_4); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_1}, new JPanel[]{ind_2,ind_3, ind_1});
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseReleased
        // TODO add your handling code here:
          setColor(btn_2); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_3,btn_4}, new JPanel[]{ind_1,ind_3, ind_4});
    }//GEN-LAST:event_btn_2MouseReleased

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseMoved
        // TODO add your handling code here:
         setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4}, new JPanel[]{ind_2,ind_3, ind_4});
    }//GEN-LAST:event_btn_1MouseMoved

    private void btn_3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseMoved
        // TODO add your handling code here:
        setColor(btn_3); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_1,btn_4}, new JPanel[]{ind_2,ind_1, ind_4});
    }//GEN-LAST:event_btn_3MouseMoved

    private void btn_4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseMoved
        // TODO add your handling code here:
        setColor(btn_4); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_1}, new JPanel[]{ind_2,ind_3, ind_1});
    }//GEN-LAST:event_btn_4MouseMoved

    private void btn_2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseMoved
        setColor(btn_2); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_3,btn_4}, new JPanel[]{ind_1,ind_3, ind_4});        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2MouseMoved

    private void update_dataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_dataMouseMoved
        update_data.setBackground(Color.yellow);
    }//GEN-LAST:event_update_dataMouseMoved

    private void update_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_dataActionPerformed
          Apiaries apia = new Apiaries();
            viz_data.setBackground(Color.white);
            viz_data.setPreferredSize(new Dimension(1167, 562));
           viz_data.removeAll();
           viz_data.setLayout(new BorderLayout());
           if(combo_location.getItemCount()!=0 || combo_apia.getItemCount()!=0){
           viz_data.add(apia.chartpanel(combo_location.getSelectedItem().toString(),
                   combo_apia.getSelectedItem().toString()),BorderLayout.CENTER);}
           viz_data.validate();
           viz_data.repaint();
           
    }//GEN-LAST:event_update_dataActionPerformed

    private void combo_apiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_apiaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_apiaItemStateChanged

    private void combo_apiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_apiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_apiaActionPerformed

    private void combo_locationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_locationItemStateChanged
       if(combo_location.getItemCount()!=0) {ListFill();}
    }//GEN-LAST:event_combo_locationItemStateChanged

    private void combo_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_locationActionPerformed

    private void synchro_apiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synchro_apiaActionPerformed
        Apiaries apia = new Apiaries();
        if(!editState){
            combo_loc.removeAllItems();
            Combofill(apia.dir(Constants.ABSULUTE_PATH));
            if(combo_loc.getSelectedItem().hashCode()!=0) ListFill();}
    }//GEN-LAST:event_synchro_apiaActionPerformed

    private void synchro_apiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_synchro_apiaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_synchro_apiaMouseMoved

    private void delete_apiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_apiaActionPerformed
        Apiaries apia = new Apiaries();
        if(combo_loc.getSelectedItem().hashCode()!=0 && !apia_List.isSelectionEmpty()){
            String msg=apia.Remove_apiary(new File(Constants.ABSULUTE_PATH+"/"+
                combo_loc.getSelectedItem().toString()+"/"+apia_List.getSelectedValue()));
        showMessageDialog(null, msg);
        }
        else{
            showMessageDialog(null, "please select  apiary to delete !");
        }
    }//GEN-LAST:event_delete_apiaActionPerformed

    private void delete_apiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_apiaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_apiaMouseMoved

    private void edit_apiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_apiaActionPerformed
        if(combo_loc.getSelectedItem().hashCode()!=0 && !apia_List.isSelectionEmpty()){
            try {
                Editapiary edi_api = new Editapiary();
                edi_api.loc_txt.setText(combo_loc.getSelectedItem().toString());
                edi_api.oldloc=combo_loc.getSelectedItem().toString();
                edi_api.oldname= apia_List.getSelectedValue();
                edi_api.ref_txt.setText( apia_List.getSelectedValue());
                edi_api.setVisible(true);

            } catch (ParseException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }  }else{
                showMessageDialog(null, "please select location and apiary to edit !");
            }
    }//GEN-LAST:event_edit_apiaActionPerformed

    private void edit_apiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_apiaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_apiaMouseMoved

    private void add_apiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_apiaActionPerformed
        try {
            Addapiary win = new Addapiary();
            win.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_add_apiaActionPerformed

    private void add_apiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_apiaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_add_apiaMouseMoved

    private void combo_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_locActionPerformed

    private void combo_locItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_locItemStateChanged
        if(combo_loc.getItemCount()!=0) {ListFill();}
    }//GEN-LAST:event_combo_locItemStateChanged

    private void apia_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apia_ListMouseClicked
        TT_table.setModel(new DefaultTableModel());
        W_table.setModel(new DefaultTableModel());
        tablesFill("TTdata.csv",TT_table);
        tablesFill("Wdata.csv",W_table);
        tableRender colorRenderer = new tableRender();
        colorRenderer.type_C=Constants.typecolumn_temp;
        TableColumnModel columnModel = TT_table.getColumnModel();
        int cc = columnModel.getColumnCount();
        if(cc>=3){
            TableColumn column = columnModel.getColumn(2);
            column.setCellRenderer(colorRenderer);
            colorRenderer = new tableRender();
            colorRenderer.type_C=Constants.typecolumn_traffic;
            column = columnModel.getColumn(3);
            column.setCellRenderer(colorRenderer);
        }
        progCell rend_prog=new progCell(0,100);
        columnModel = W_table.getColumnModel();
        cc = columnModel.getColumnCount();
        for(int i=0;i<cc;i++){
            TableColumn column = columnModel.getColumn(i);
            column.setCellRenderer(rend_prog);
        }
        Font bigFont = new Font("sansserif", Font.PLAIN, 24); // or whatever
        TT_table.getTableHeader().setFont(bigFont);
        setMax(TT_table);
        W_table.getTableHeader().setFont(bigFont);
    }//GEN-LAST:event_apia_ListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(248,196,18));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(105,48,44));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
  //table temp/traffic
    private void tablesFill(String type,javax.swing.JTable T){
    Apiaries apia = new Apiaries();
    String loc= combo_loc.getSelectedItem().toString();
    String apia_name= apia_List.getSelectedValue();
    if(apia_name !=null){
        apia.Fill_Tale(Constants.ABSULUTE_PATH+"/"+loc+"/"+apia_name+"/"+type);
        DefaultTableModel model = (DefaultTableModel)T.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(apia.getTableCulumns());
        for (Object tableLine : apia.getTableRows()) {
                        String line = tableLine.toString().trim();
                        String[] dataRow = line.split(","); 
                        for (int i=0;i<dataRow.length;i++){
                            if(dataRow[i].equals(""))dataRow[i]="no data"; 
                        }
                        model.addRow(dataRow);
                               }
                      }  
    }
    private void setMax(javax.swing.JTable T)
    {
        int max_temp = 0;
        int max_traffic=0;
        
        for(int i = 0; i < T.getRowCount(); i++)
        {
            int val_temp = 0;
            int val_traffic=0;
         if(T.getValueAt(i, 2)!=null) val_temp = Integer.parseInt(T.getValueAt(i, 2).toString());
         if(T.getValueAt(i, 3)!=null) val_traffic = Integer.parseInt(T.getValueAt(i, 3).toString());
          if(val_temp > max_temp)
          {
              max_temp = val_temp;
          }
          if(val_traffic > max_traffic)
          {
              max_traffic = val_traffic;
          }
        }
         temp_max.setText(Integer.toString(max_temp));
         traffic_max.setText(Integer.toString(max_traffic));
    }
    private void ListFill(){
         Apiaries apia = new Apiaries();
         String loc= combo_loc.getSelectedItem().toString();
         String[] apidir=apia.dir(Constants.ABSULUTE_PATH+"/"+loc);
       apia_List.setListData(apidir);
        if(combo_location.getItemCount()!=0) {
            loc=combo_location.getSelectedItem().toString();
        } 
       apidir=apia.dir(Constants.ABSULUTE_PATH+"/"+loc);
       combo_apia.removeAllItems();
        for(String api:apidir){
            combo_apia.addItem(api);
        }
    }     
    private void Combofill(String [] curDir){      
        for(String d:curDir){
          combo_loc.addItem(d);
          combo_location.addItem(d);}
        }
    
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pane_home;
    private javax.swing.JTable TT_table;
    private javax.swing.JTable W_table;
    private javax.swing.JButton add_apia;
    private javax.swing.JList<String> apia_List;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JComboBox<String> combo_apia;
    private javax.swing.JComboBox<String> combo_loc;
    private javax.swing.JComboBox<String> combo_location;
    private javax.swing.JButton delete_apia;
    private javax.swing.JButton edit_apia;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel name_dash;
    private javax.swing.JPanel side_pane;
    private javax.swing.JButton synchro_apia;
    private javax.swing.JLabel temp_max;
    private javax.swing.JLabel traffic_max;
    private javax.swing.JButton update_data;
    private javax.swing.JPanel viz_data;
    private javax.swing.JPanel viz_panel;
    // End of variables declaration//GEN-END:variables
}
